### ISSUE TITLE
[1.20-1.2.1] Fails to start on server - Loads client-only class

### ISSUE THREAD

**Issue by TigerWalts** [nyuppo/MobVariantsForge#1]
This is similar to the bug in the Fabric version (https://github.com/nyuppo/MobVariants/commit/41fcc5ccb263549656b86b0ddf1aab4c9a9026ce)

- https://pastebin.com/gJspFaP1

```
	Caused by 1: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/EntityRendererProvider$Context
                ...
		at com.github.nyuppo.MoreMobVariants.<init>(MoreMobVariants.java:73) ~[moremobvariants-forge+1.20-1.2.1.jar%23257!/:1.2.1] {re:mixin,re:classloading}
```

**Comment by nyuppo** [comment]
Just pushed a 1.2.2 update that should fix this problem! You're totally right, not sure how I noticed to fix this bug in the fabric version but not the forge version.
